version: "2"

services:
  snaxnoded:
    image: snax/snax:v1.1.4
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  branch: master

    command: /opt/snax/bin/snaxnoded.sh --verbose-http-errors --max-transaction-time=1000 --data-dir /opt/snax/bin/data-dir -e --http-alias=snaxnoded:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: snaxnoded
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"

  kxd:
    image: snax/snax:v1.1.4
    command: /opt/snax/bin/kxd --wallet-dir /opt/snax/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kxd:8900 --http-alias=localhost:8900
    hostname: kxd
    ports:
      - 8900:8900
    links:
      - snaxnoded
